# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.3.0"

pre_release = true

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.2/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]


    [notes.updates]
        title = "Component Updates"
        description = """\
* Gvisor: 20230109.0
* Linux firmware: 20221214
"""


[make_deps]
