# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.7.0"

pre_release = true

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.8/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]

[notes.updates]
    title = "Component Updates"
    description = """
ZFS: 2.2.4
DRBD: 9.2.9
gasket: 5815ee3
Tailscale: 1.64.2
ecr-credential-provider: 1.30.2
qemu-guest-agent: 9.0.1
mdadm: 4.3
Intel microcode: 20240531
Linux firmware: 20240513
Spin: 1.5.0
Gvisor: 20240624.0
Wasmedge: v0.4.0
Kata Containers: 3.6.0
NVIDIA container toolkit: v1.15.0
iscsi-tools: v0.1.5
"""


[make_deps]
