# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.2.1"

pre_release = false

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.2/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]

    [notes.power]
        title = "Power management"
        description = """\
Support for Network UPS Tools client system extension to handle node graceful shutdown on power events from supported UPS's.
"""


[make_deps]
